initial commit first-iteration
NotUrBruddah/go-first-floor-sprint-five pull request #1
Opened 2024-06-11 21:35 UTC by NotUrBruddah

2024-06-11 23:35 UTC, dirtymew requested changes
Привет Андрей

отличная работа - ошибка только в одной формуле

2024-06-11 23:35 UTC, dirtymew commented on main.go
> +	return t.distance() / t.Duration.Hours()
тут возможно деление на 0

2024-06-11 23:35 UTC, dirtymew commented on main.go
> +	return float64(0)
можно просто return 0

2024-06-11 23:35 UTC, dirtymew commented on main.go
> +	trainingMessage := InfoMessage{
trainingMessage на мой взгляд лишняя переменная

2024-06-11 23:35 UTC, dirtymew commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow((w.meanSpeed()*KmHInMsec), 2)/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
тут ошибка в формуле - проверь что все константы были использованы

подскажу w.Height в см


и еще тут деление на 0 возможно

2024-06-12 16:06 UTC, NotUrBruddah commented
Скорректировано по рекомендациям , закоммитил изменения

2024-06-12 16:07 UTC, NotUrBruddah commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow((w.meanSpeed()*KmHInMsec), 2)/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Исправил, вывел предупреждения о неверных параметрах или их отсутствиях

2024-06-12 16:07 UTC, NotUrBruddah commented on main.go
> +	trainingMessage := InfoMessage{
исправил

2024-06-12 16:07 UTC, NotUrBruddah commented on main.go
> +	return float64(0)
исправил

2024-06-12 16:07 UTC, NotUrBruddah commented on main.go
> +	return t.distance() / t.Duration.Hours()
проверил, вывел предупреждение о ошибке

2024-06-12 16:08 UTC, NotUrBruddah commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow((w.meanSpeed()*KmHInMsec), 2)/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
формулу исправил

2024-06-12 19:15 UTC, dirtymew approved these changes
Привет Андрей

задание выполнено - зачет

2024-06-12 19:15 UTC, dirtymew commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow((w.meanSpeed()*KmHInMsec), 2)/(w.Height/100))*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
для этого была константа CmInM

2024-06-13 00:21 UTC, NotUrBruddah commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow((w.meanSpeed()*KmHInMsec), 2)/(w.Height/100))*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Да , действительно, из за го что константа далеко вверху ее и не заметил

2024-06-13 00:27 UTC, NotUrBruddah commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow((w.meanSpeed()*KmHInMsec), 2)/(w.Height/100))*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Исправил

2024-06-13 00:33 UTC, merged